UGM_Database/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from UGM_Database import settings
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

def Print(value):
    print '\n\n\n\n',value

test = [i for i in settings.INSTALLED_APPS if i in ['guestmanagement','truckmanagement','purchaseorder']]


def index(request):
    sites = {'guestmanagement':'Guest Management',
             'truckmanagement':'Truck Management',
             'purchaseorder':'Purchase Orders',
    }
    if len(test)==1:
        return redirect('/%s/'%test[0])
    html = ' or '.join(["<a href='/%s/'>%s</a>"%(i,sites[i]) for i in test])
    return HttpResponse(html)

urlpatterns = [url(r'^%s/'%i, include('%s.urls'%i)) for i in test]

'''
urlpatterns = [
    # Examples:
    # url(r'^$', 'UGM_Database.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^truckmanagement/', include('truckmanagement.urls')),
    url(r'^report_builder/', include('report_builder.urls')),
    url(r'^guestmanagement/',include('guestmanagement.urls')),
]
'''

#urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns.append(url(r'^admin/', include(admin.site.urls)))
urlpatterns.append(url(r'^',index,name='index'))

guestmanagement/urls.py
from django.conf.urls import url,include
from guestmanagement import views


urlpatterns = [
        url(r'^$',views.index,name='index'),
        url(r'^guestlogin/(?P<target_guest>.+)/$',views.guestlogin,name='guestlogin'),
        url(r'^guestlogin/$',views.guestlogin,name='guestlogin'),
        url(r'^manage/(?P<target_type>.+)/(?P<target_object>.+)/',views.manage,name='manage'),
        url(r'^manage/(?P<target_type>.+)/',views.manage,name='manage'),
        url(r'^manage/$',views.manage,name='manage'),
        url(r'^view/(?P<target_type>.+)/(?P<target_object>.+)/(?P<second_object>.+)/',views.view,name='view'),
        url(r'^view/(?P<target_type>.+)/(?P<target_object>.+)/',views.view,name='view'),
        url(r'^unsetcomplete/(?P<form_id>.+)/(?P<guest_id>.+)/',views.unsetcomplete,name='unsetcomplete'),
        url(r'^setscore/(?P<form_id>.+)/(?P<guest_id>.+)/',views.setscore,name='setscore'),
        url(r'^runreport/(?P<report_id>.+)/',views.runreport,name='runreport'),
        url(r'^logout/$',views.logout,name='logout'),
        url(r'^edit/(?P<target_guest>.+)/(?P<target_form>.+)/(?P<target_guesttimedata>.+)/$',views.editpastform,name='edit'),
        url(r'^edit/(?P<target_guest>.+)/(?P<target_form>.+)/$',views.editpastform,name='edit'),
        url(r'^quickfilter/$',views.quickfilter,name='filter'),
]

guestmanagement/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os

class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name):
        self.delete(name)
        return name

def guestPictureNamer(instance, filename):
	return 'guestpictures/%s.%s'%(instance.id,filename.split('.')[-1])

# Create your models here.

class User_Permission_Setting(models.Model):
    user = models.ForeignKey(User)
    permissions = models.ManyToManyField("Permission",null=True,blank=True)
    def __unicode__(self):
        return self.user.username

    def permissions_list(self):
        return ' | '.join([i.__unicode__() for i in self.permissions.all()])

    class Meta:
        permissions = (
            ('view_user_permission_settings', 'Can See Permissions by User'),
            ('manage_user_permission_settings', 'Can Set Permissions by User'),
        )

class DynamicFilePermissions(models.Model):
    path = models.CharField(max_length=200)
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='dynamic_form_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='dynamic_form_must')
    guest = models.ForeignKey("Guest",null=True,blank=True)
    form = models.ForeignKey("Form", null=True,blank=True)
    field = models.ForeignKey("Field", null=True,blank=True)
    program = models.ManyToManyField("Program",null=True,blank=True)

    def __unicode__(self):
        return self.path


class Attachment(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200, unique=True)
    attachment = models.FileField(upload_to='staticforms')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='static_form_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='static_form_must')
    def __unicode__(self):
        return self.name
    class Meta:
        permissions = (
            ('view_attachment', 'Can See Attachments'),
            ('manage_attachment', 'Can Manage Attachments'),
        )


class Program(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_must')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_write')

    def __unicode__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_program', 'Can See Programs'),
            ('manage_program', 'Can Manage Programs'),
        )


class Form(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    program = models.ManyToManyField(Program)
    form_prerequisite = models.ManyToManyField('Prerequisite', null=True, blank=True)
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='must')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='may')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='form_write')
    guest_completable = models.BooleanField(default=False)
    lock_when_complete = models.BooleanField(default=False)
    auto_grade = models.BooleanField(default=False)
    single_per_day = models.BooleanField(default=False)

    def program_list(self):
        return ' | '.join([i.name for i in self.program.all()])

    def __unicode__(self):
        return self.name

    def prerequisite_list(self):
        return ' | '.join([i.name for i in self.form_prerequisite.all()])

    class Meta:
        permissions = (
            ('view_form', 'Can See Forms'),
            ('manage_form', 'Can Manage Forms'),
        )


class Field(models.Model):
    owner = models.ManyToManyField(User)
    order = models.SmallIntegerField(null=True)
    name = models.CharField(max_length=200)
    label = models.CharField(max_length=200, blank=True, null=True)
    form = models.ForeignKey(Form, null=True)
    extra_forms = models.ManyToManyField('Form', null=True, blank=True, related_name='form_extra')
    field_type = models.CharField(choices=(('text_box', 'Text Box'),
                                           ('comment_box', 'Comment Box'),
                                           ('drop_down', 'Drop Down'),
                                           ('boolean', 'Check Box'),
                                           ('list', 'List'),
                                           ('date', 'Date'),
                                           ('url', 'URL'),
                                           ('attachment', 'Attachment'),
                                           ('file','File'),
                                           ('title','Section Title'),
                                           ), max_length=200)
    attachment = models.ForeignKey(Attachment,blank=True,null=True)
    external_url = models.CharField(max_length=2000, blank=True, default='')
    dropdown_options = models.CharField(max_length=2000, blank=True, default='')
    time_series = models.BooleanField(default=False)
    field_prerequisite = models.ManyToManyField('Prerequisite', null=True, blank=True)
    required = models.BooleanField(default=False)
    add_only = models.BooleanField(default=False)
    blank_each_time = models.BooleanField(default=False)
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_must')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_may')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_write')
    correct_answer = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def prerequisite_list(self):
        return ' | '.join([i.name for i in self.field_prerequisite.all()])

    class Meta:
        permissions = (
            ('view_field', 'Can See Fields'),
            ('manage_field', 'Can Manage Fields'),
            ('change_fixed_field','Can Erase Notes')
        )


class Guest(models.Model):
    first_name = models.CharField(max_length=200, blank=True, null=True)
    middle_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    ssn = models.CharField(max_length=9, blank=True, null=True)
    program = models.ManyToManyField(Program)
    picture = models.ImageField(upload_to=guestPictureNamer,storage=OverwriteStorage())
    password = models.CharField(max_length=2000, blank=True, null=True)
    barcode = models.CharField(max_length=2000, blank=True, null=True)

    def clean(self):
        if self.ssn=='':
            self.ssn=None

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def program_list(self):
        return ' | '.join([i.name for i in self.program.all()])

    def last_4_ssn(self):
        if self.ssn:
            return u'%s' % self.ssn[-4:]
        return u''

    def image_tag(self,height=42,width=42):
        return mark_safe(u'<img src="%s" height="%s" width="%s"/>' % (self.picture.url,height,width))

    def name(self):
        return '%s %s' % (self.first_name.capitalize(), self.last_name.capitalize())

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    class Meta:
        permissions = (
            ('view_guest', 'Can See Guests'),
            ('manage_guest', 'Can Manage Guests'),
        )


class Permission(models.Model):
    owner = models.ManyToManyField(User,related_name='permission_owner')
    name = models.CharField(max_length=2000, unique=True)
    users = models.ManyToManyField(User, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def user_list(self):
        return ' | '.join([i.__unicode__() for i in self.users.all()])

    class Meta:
        permissions = (
            ('view_permission', 'Can See Permissions'),
            ('manage_permission', 'Can Manage Permissions'),
        )


class Prerequisite(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=2000, blank=True, null=True)
    prerequisite_form = models.ManyToManyField(Form, blank=True, null=True)
    prerequisite_field = models.ManyToManyField(Field, blank=True, null=True)
    is_complete = models.BooleanField(default=False)
    score_is_greater_than = models.CharField(max_length=2000, blank=True, null=True)
    is_value = models.CharField(max_length=2000, blank=True, null=True)
    contains = models.CharField(max_length=2000, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def form_list(self):
        return ' | '.join([i.name for i in self.prerequisite_form.all()])

    def field_list(self):
        return ' | '.join([i.name for i in self.prerequisite_field.all()])

    class Meta:
        permissions = (
            ('view_prerequisite', 'Can See Prerequisites'),
            ('manage_prerequisite', 'Can Manage Prerequisites'),
        )


class GuestTimeData(models.Model):
    date = models.DateTimeField(null=True, blank=True)
    guest = models.ForeignKey(Guest)
    field = models.ForeignKey(Field)
    value = models.CharField(max_length=20000, blank=True, null=True, default='')


class GuestData(models.Model):
    date = models.DateTimeField(null=True, blank=True)
    guest = models.ForeignKey(Guest)
    field = models.ForeignKey(Field)

guestmanagement/forms.py
from guestmanagement.models import Guest,Program,Form,Field,Prerequisite,Permission,Report,Attachment,User_Permission_Setting
from django import forms
from django.utils.safestring import mark_safe

class NewUser_Permission_Setting(forms.ModelForm):
	class Meta:
		model=User_Permission_Setting
		exclude=[]
		list_filter = [['user','many','username','icontains']]
		list_display = ['user','permissions_list']

class NewGuestForm(forms.ModelForm):
	class Meta:
		model=Guest
		exclude=[]
		widgets = {'password': forms.PasswordInput(),'barcode': forms.PasswordInput()}
		list_filter = [['first_name','icontains'],['last_name','icontains'],['ssn','endswith'],['program','many','name','icontains'],['barcode','exact']]
		list_display = ['id','first_name','last_name','last_4_ssn','program_list','image_tag']

class NewProgramForm(forms.ModelForm):
	class Meta:
		model=Program
		exclude=[]
		list_filter = [['name','icontains']]
		list_display = ['name']

class NewFormForm(forms.ModelForm):
	class Meta:
		model=Form
		exclude=[]
		list_filter = [['name','icontains'],['program','many','name','icontains'],['form_prerequisite','many','name','icontains']]
		list_display = ['name','program_list','prerequisite_list']

class NewFieldForm(forms.ModelForm):
	dropdown_options = forms.CharField(widget=forms.Textarea(attrs={'size': 100, }),required=False)
	class Meta:
		model=Field
		exclude=['order']
		list_filter = [['name','icontains'],['form','many','name','icontains'],['label','icontains'],['field_type','icontains']]
		list_display = ['name','form','label','field_type','prerequisite_list']

class NewPrerequisiteForm(forms.ModelForm):
	class Meta:
		model=Prerequisite
		exclude=[]
		list_filter = [['name','icontains'],['prerequisite_form','many','name','icontains'],['prerequisite_field','many','name','icontains']]
		list_display = ['name','form_list','field_list','is_complete','is_value']

class NewPermissionsForm(forms.ModelForm):
	class Meta:
		model=Permission
		exclude=[]
		list_filter = [['name','icontains'],]
		list_display = ['name','user_list']

class NewReportForm(forms.ModelForm):
	description = forms.CharField(widget=forms.Textarea(),required=False)
	class Meta:
		model=Report
		exclude=[]
		fields=['name','owner','description','permissions_must_have','permissions_may_have']
		list_filter = [['name','icontains']]
		list_display = ['name','owner_list']

class NewAttachmentForm(forms.ModelForm):
	class Meta:
		model=Attachment
		exclude=[]
		list_filter = [['name','icontains'],]
		list_display = ['name']

guestmanagement/templates/guestmanagement/edit.html
{% extends "shared/base.html" %}{% load i18n %}{% load staticfiles %}
{% block pretitle %}
    <h1>{% trans 'Edit Guest' %} {{ target_guest.name }}'s {{ target_form }} form:</h1><br/>
{% endblock %}
{% block content %}
    {% if link_list != 'no links' %}
        {% if not link_list %}
            No valid forms to edit
        {% else %}
            Pick date to edit: <br />
            {% for i in link_list %}
                <a href='/guestmanagement/edit/{{ target_guest.id }}/{{ target_form.id }}/{{ i.1 }}/'>{{ i.0 }}</a><br />
            {% endfor %}
        {% endif %}
    {% else %}
        <form action='.' method='post' autocomplete="off" name="DeleteForm">
            {% csrf_token %}
            {% if "guestmanagement.delete_guesttimedata" in perms %}
                <input id='delete' type='text' name='delete' value='delete' hidden>
                <input type='button' value='Delete {{ target_type.capitalize }}' onclick="formSubmitConfirm('DeleteForm','Confirm Delete {{ target_type.capitalize }}')">
            {% endif %}
        </form>
        <form action='.' method='post' autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            New Date: <input class='datePicker' id='changeDate' name='changeDate' readonly='true' type='text'></br>
            New Time: <input class='timePicker' id='changeTime' name='changeTime' readonly='true' type='text'></br>
        {{ form }}
        <input id='search' type='submit' value='Submit'>
        </form>
    {% endif %}
{% endblock %}

guestmanagement/templates/guestmanagement/guestlogin.html
{% extends "shared/base.html" %}{% load i18n %}{% load staticfiles %}
{% block authenticationoverride %}
	<script type="text/javascript" src='{% static "guestmanagement/js/focusbarcode.js" %}'></script>
	{% if not guest_list and not guest_login %}
		<form action='.' method='post'>
			{% csrf_token %}
			Last 4 ssn: <input type="text" name="ssn"> or Last Name <input type="text" name="last_name"> or ID Number <input type="text" name="id"> or barcode <input type="password" name="barcode"><br>
			<input type='submit' value='Submit' name='submit'/>
		</form>
	{% elif guest_list %}
        Select your name</br>
        Last name, First name, Id</br>
		{% for i in guest_list %}
			<a href='/guestmanagement/guestlogin/{{ i.1 }}/'>{{ i.0 }}, {{ i.2 }}, {{ i.1 }}</a></br>
		{% endfor %}
        </br></br>
        <a href="/guestmanagement/guestlogin/">Try another search</a>
	{% else %}
		<form action='.' method='post'>
			{% csrf_token %}
            Guest name starts with</br></br> {{ guest_name }}</br></br>
			Password: <input type="password" name="password">
			<input type='submit' value='Login' name='login'/>
		</form>
	{% endif %}
{% endblock %}

guestmanagement/templates/guestmanagement/quickfilter.html
{% extends "shared/base.html" %}{% load i18n %}{% load staticfiles %}
{% block title %}
	{% trans 'Quick Filter' %}
{% endblock %}
{% block pretitle %}
	<h1>Quick Filter:</h1><br />
{% endblock %}
{% block content %}
	<input name='field_list' id='field_list' value="{{ field_list }}" hidden />
	<input name='form_list' id='form_list' value="{{ form_list }}" hidden />
	<input name='submitted_form' id='submitted_form' value="{{ submission.0 }}" hidden />
	<input name='submitted_field' id='submitted_field' value="{{ submission.1 }}" hidden />
	<input name='submitted_criteria' id='submitted_criteria' value="{{ submission.2 }}" hidden />
	<script type="text/javascript" src="{% static "guestmanagement/js/quickfilter.js" %}"></script>
	<form action='.' method='post' autocomplete="off" enctype="multipart/form-data">
		{% csrf_token %}
		<div id='query_loading'>
			Load Query:
			<select name='load_query'>
				<option value = ''></option>
				{% for i in query_list %}
					<option value='{{ i.name }}'>{{ i.name }}</option>
				{% endfor %}
			</select>
			<input id='load' name='load' type='submit' value='Load' />
		</div>
		<div id='form_select_div'></div>
		<div id='field_select_div'></div>
		<div id='filter_div'></div>
		<input id='search' name='search' type='button' value='Submit' onclick="verifySubmit(this)" hidden>
		<label id='save_label' for="save" hidden>Save Query:</label><input id='save' name='save' type='checkbox' onclick='toggleName();' hidden />
		<label id='save_name_label' for="save_name" hidden>Query Name:</label><input name='save_name' id='save_name' hidden />
		<div id='viewer_div'>
			{% if form %}
				{{ form }}
				{% if write_perm %}
					<input id='change' name='change' type='button' value='Commit' onclick="verifySubmit(this)">
				{% endif %}
			{% endif %}
		</div>
	</form>
{% endblock %}

guestmanagement/templates/guestmanagement/report.html
{% extends "shared/base.html" %}{% load i18n %}{% load staticfiles %}
{% block title %}
	{{ report_name }}
{% endblock %}

{% block content %}
	<a href='{{ download_path }}'>Download Report</a><br />
	{{ report }}
{% endblock %}

guestmanagement/templates/guestmanagement/setscore.html
{% extends "guestmanagement/base.html" %}{% load i18n %}
{% block content %}
	<h1>Set Score on form {{ target_form }} for {{ target_guest }}</h1>
	<form action='#' method='post'>
		{% csrf_token %}
		<input id='score' type='text' name='score'><br>
		<input id='submit' type='submit' name='submit' value='Change'>
	</form>
{% endblock %}

guestmanagement/templates/guestmanagement/view.html
{% extends "shared/base.html" %}{% load i18n %}{% load staticfiles %}
{% block title %}
	{% trans 'View' %} {{ target_type.capitalize }} {{ target_object.name }}{% if target_object.label %} (aka {{ target_object.label }}){% endif %}
{% endblock %}
{% block pretitle %}
	<h1>{% trans 'View' %} {{ target_type.capitalize }} {{ target_object.name }}{% if target_object.label %} (aka {{ target_object.label }}){% endif %}:</h1><br/>
	{% if "guestmanagement.manage_"|add:target_type in perms and "guestmanagement.change_"|add:target_type in perms %}
		<a href='/guestmanagement/manage/{{ target_type }}/{{ target_object.id }}/'>Manage {{ target_type }} {{ target_object.name }}</a></br>
	{% endif %}
{% endblock %}
{% block content %}
	{{ view_image }}</br>
	{% if guest_logged_in %}<a href='/guestmanagement/logout/'>Logout</a>{% endif %}
	{% if target_type == 'guest' %}
		<table>
			<tr><th>Form Name</th></tr>
			{% for i in form_list %}
				<tr>
					<td>{{ i.0 }}</td>
					{% if i.1 != 'Completed' or not i.2 or perms.guestmanagement.change_guestformscompleted %}
						<td><a href='/guestmanagement/view/form/{{ i.0.id }}/{{ target_object.id }}/?next={{ nexturl }}'>Complete Form</a></td>
					{% else %}
						<td></td>
					{% endif %}
					{% if perms.guestmanagement.view_forms or perms.guestmanagement.manage_forms %}
						<td><a href='/guestmanagement/view/form/{{ i.0.id }}/?next={{ nexturl }}'>Edit Form</a></td>
					{% endif %}
					<td>{{ i.1 }}</td>
					{% if i.3 %}
						<td>{{ i.3 }}%</td>
					{% endif %}
					{% if i.2 and i.1 == 'Completed' and perms.guestmanagement.delete_guestformscompleted %}
						<td><a href='/guestmanagement/unsetcomplete/{{ i.0.id }}/{{ target_object.id }}/?next={{ nexturl }}'>Set Incomplete</a></td>
					{% endif %}
					{% if i.4 and perms.guestmanagement.change_guestformscompleted  %}
						<td><a href='/guestmanagement/setscore/{{ i.0.id }}/{{ target_object.id }}/?next={{ nexturl }}'>Set Score</a></td>
					{% endif %}
                    {% if perms.guestmanagement.change_guesttimedata %}
                        <td><a href='/guestmanagement/edit/{{ target_object.id }}/{{ i.0.id }}/'>Edit Past Form</a></td>
                    {% endif %}
				</tr>
			{% endfor %}
		</table>

	{% elif target_type == 'form' %}
		{% if second_object %}
			<form action='.' method='post' enctype="multipart/form-data">
				{% csrf_token %}
				{{ form }}
				{% if user.is_authenticated and write_perm%}
					<div class="floating_button">
						<input type='button' value='Update' class="floating_button" onclick='scrollReturn(this)'/>
						{% if required_failed %}
							<br />
							<br />
							<p class='errornote'>Enter All Required Fields</p>
						{% endif %}
					</div>
				{% endif %}
				{% if write_perm %}
					<input type='submit' value='Submit and Continue' name='submit_form'/>
				{% else %}
					<input type='submit' value='Continue' name='submit_form'/>
				{% endif %}
			</form>
		{% else %}
			<table>
				<tr><th>Field Name</th><th>Field Order</th></tr>
				{% for i in field_list %}
					<tr>
						<td><a href='/guestmanagement/view/field/{{ i.id }}/'>{{ i.label }}</a></td>
						<td>{{ i.order }}</td>
						{% if write_perm %}
							<td>
								<form action='.' method='post'>
									{% csrf_token %}
									<input id='move_type' type='text' name='move_type' value='up' hidden>
									<input id='move_field' type='text' name='move_field' value='{{ i.id }}' hidden>
									<input id='search' type='submit' value='Up' onclick='scrollReturn(this)'>
								</form>
							</td>
							<td>
								<form action='.' method='post'>
									{% csrf_token %}
									<input id='move_type' type='text' name='move_type' value='down' hidden>
									<input id='move_field' type='text' name='move_field' value='{{ i.id }}' hidden>
									<input id='search' type='submit' value='Down' onclick='scrollReturn(this)'>
								</form>
							</td>
							<td>
								<form action='.' method='post'>
									{% csrf_token %}
									<input id='move_type' type='text' name='move_type' value='top' hidden>
									<input id='move_field' type='text' name='move_field' value='{{ i.id }}' hidden>
									<input id='search' type='submit' value='Top' onclick='scrollReturn(this)'>
								</form>
							</td>
							<td>
								<form action='.' method='post'>
									{% csrf_token %}
									<input id='move_type' type='text' name='move_type' value='bottom' hidden>
									<input id='move_field' type='text' name='move_field' value='{{ i.id }}' hidden>
									<input id='search' type='submit' value='Bottom' onclick='scrollReturn(this)'>
								</form>
							</td>
						{% endif %}
					</tr>
				{% endfor %}
			</table>
		{% endif %}
	{% elif target_type == 'report' %}
		{{ target_object.description }}</br>
		<script type="text/javascript" src='{% static "guestmanagement/js/report.js" %}'></script>
		{% if variables %}
			<table>
				<tr><th>Variable Name</th><th>Value</th></tr>
				{% for i in variables %}
					<tr>
						<td>
							{{ i.0 }}
						</td>
						<td>
							{% if i.1 %}
								<select name='variable__{{ i.0 }}' />
								{% for a in i.1 %}
									<option value='{{ a }}'>{{ a }}</option>
								{% endfor %}
							{% else %}
								<input name='variable__{{ i.0 }}' />
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</table>
		{% endif %}
		<a href='/guestmanagement/runreport/{{ target_object.id }}/' onclick=runReport(this)>Run Report</a>
	{% endif %}
	{% if link_list %}
		{% for i in link_list %}
			<h5>{{ i.0 }}</h5></br>
			{% for a in i.2 %}
				{% if i.1 != 'nolink' %}
					<a href='/guestmanagement/view/{{ i.1 }}/{{ a.id }}/'>{{ a }}</a></br>
				{% else %}
					{{ a }}</br>
				{% endif %}
			{% endfor %}
		{% endfor %}
	{% endif %}
{% endblock %}