UGM_Database/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from UGM_Database import settings
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

def Print(value):
    print '\n\n\n\n',value

test = [i for i in settings.INSTALLED_APPS if i in ['guestmanagement','truckmanagement','purchaseorder']]


def index(request):
    sites = {'guestmanagement':'Guest Management',
             'truckmanagement':'Truck Management',
             'purchaseorder':'Purchase Orders',
    }
    if len(test)==1:
        return redirect('/%s/'%test[0])
    html = ' or '.join(["<a href='/%s/'>%s</a>"%(i,sites[i]) for i in test])
    return HttpResponse(html)

urlpatterns = [url(r'^%s/'%i, include('%s.urls'%i)) for i in test]

'''
urlpatterns = [
    # Examples:
    # url(r'^$', 'UGM_Database.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^truckmanagement/', include('truckmanagement.urls')),
    url(r'^report_builder/', include('report_builder.urls')),
    url(r'^guestmanagement/',include('guestmanagement.urls')),
]
'''

#urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns.append(url(r'^admin/', include(admin.site.urls)))
urlpatterns.append(url(r'^',index,name='index'))

report_builder/urls.py
from django.conf.urls import patterns, url
from django.contrib.admin.views.decorators import staff_member_required
from report_builder import views

urlpatterns = patterns('',
    url('^report/add/$',  views.ReportCreateView.as_view(), name="report_create"),
    url('^report/(?P<pk>\d+)/$', views.ReportUpdateView.as_view(), name="report_update_view"),
    url('^report/(?P<pk>\d+)/check_status/(?P<task_id>.+)/$', views.check_status, name="report_check_status"),
    url('^report/(?P<pk>\d+)/download_xlsx/$',  views.DownloadXlsxView.as_view(), name="report_download_xlsx"),
    url('^ajax_get_related/$', staff_member_required(views.AjaxGetRelated.as_view())),
    url('^ajax_get_fields/$', staff_member_required(views.AjaxGetFields.as_view())),
    url('^ajax_get_choices/$', views.ajax_get_choices, name="ajax_get_choices"),
    url('^ajax_get_formats/$', views.ajax_get_formats, name="ajax_get_formats"),
    url('^ajax_preview/$', views.AjaxPreview.as_view()),
    url('^report/(?P<pk>\d+)/add_star/$', views.ajax_add_star),
    url('^report/(?P<pk>\d+)/create_copy/$', views.create_copy),
    url('^export_to_report/$', views.ExportToReport.as_view(), name="export_to_report"),
)

guestmanagement/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os

class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name):
        self.delete(name)
        return name

def guestPictureNamer(instance, filename):
	return 'guestpictures/%s.%s'%(instance.id,filename.split('.')[-1])

# Create your models here.

class User_Permission_Setting(models.Model):
    user = models.ForeignKey(User)
    permissions = models.ManyToManyField("Permission",null=True,blank=True)
    def __unicode__(self):
        return self.user.username

    def permissions_list(self):
        return ' | '.join([i.__unicode__() for i in self.permissions.all()])

    class Meta:
        permissions = (
            ('view_user_permission_settings', 'Can See Permissions by User'),
            ('manage_user_permission_settings', 'Can Set Permissions by User'),
        )

class DynamicFilePermissions(models.Model):
    path = models.CharField(max_length=200)
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='dynamic_form_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='dynamic_form_must')
    guest = models.ForeignKey("Guest",null=True,blank=True)
    form = models.ForeignKey("Form", null=True,blank=True)
    field = models.ForeignKey("Field", null=True,blank=True)
    program = models.ManyToManyField("Program",null=True,blank=True)

    def __unicode__(self):
        return self.path


class Attachment(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200, unique=True)
    attachment = models.FileField(upload_to='staticforms')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='static_form_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='static_form_must')
    def __unicode__(self):
        return self.name
    class Meta:
        permissions = (
            ('view_attachment', 'Can See Attachments'),
            ('manage_attachment', 'Can Manage Attachments'),
        )


class Program(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_may')
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_must')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='program_write')

    def __unicode__(self):
        return self.name

    class Meta:
        permissions = (
            ('view_program', 'Can See Programs'),
            ('manage_program', 'Can Manage Programs'),
        )


class Form(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    program = models.ManyToManyField(Program)
    form_prerequisite = models.ManyToManyField('Prerequisite', null=True, blank=True)
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='must')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='may')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='form_write')
    guest_completable = models.BooleanField(default=False)
    lock_when_complete = models.BooleanField(default=False)
    auto_grade = models.BooleanField(default=False)
    single_per_day = models.BooleanField(default=False)

    def program_list(self):
        return ' | '.join([i.name for i in self.program.all()])

    def __unicode__(self):
        return self.name

    def prerequisite_list(self):
        return ' | '.join([i.name for i in self.form_prerequisite.all()])

    class Meta:
        permissions = (
            ('view_form', 'Can See Forms'),
            ('manage_form', 'Can Manage Forms'),
        )


class Field(models.Model):
    owner = models.ManyToManyField(User)
    order = models.SmallIntegerField(null=True)
    name = models.CharField(max_length=200)
    label = models.CharField(max_length=200, blank=True, null=True)
    form = models.ForeignKey(Form, null=True)
    extra_forms = models.ManyToManyField('Form', null=True, blank=True, related_name='form_extra')
    field_type = models.CharField(choices=(('text_box', 'Text Box'),
                                           ('comment_box', 'Comment Box'),
                                           ('drop_down', 'Drop Down'),
                                           ('boolean', 'Check Box'),
                                           ('list', 'List'),
                                           ('date', 'Date'),
                                           ('url', 'URL'),
                                           ('attachment', 'Attachment'),
                                           ('file','File'),
                                           ('title','Section Title'),
                                           ), max_length=200)
    attachment = models.ForeignKey(Attachment,blank=True,null=True)
    external_url = models.CharField(max_length=2000, blank=True, default='')
    dropdown_options = models.CharField(max_length=2000, blank=True, default='')
    time_series = models.BooleanField(default=False)
    field_prerequisite = models.ManyToManyField('Prerequisite', null=True, blank=True)
    required = models.BooleanField(default=False)
    add_only = models.BooleanField(default=False)
    blank_each_time = models.BooleanField(default=False)
    permissions_must_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_must')
    permissions_may_have = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_may')
    permissions_write = models.ManyToManyField('Permission', null=True, blank=True, related_name='field_write')
    correct_answer = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def prerequisite_list(self):
        return ' | '.join([i.name for i in self.field_prerequisite.all()])

    class Meta:
        permissions = (
            ('view_field', 'Can See Fields'),
            ('manage_field', 'Can Manage Fields'),
            ('change_fixed_field','Can Erase Notes')
        )


class Guest(models.Model):
    first_name = models.CharField(max_length=200, blank=True, null=True)
    middle_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    ssn = models.CharField(max_length=9, blank=True, null=True)
    program = models.ManyToManyField(Program)
    picture = models.ImageField(upload_to=guestPictureNamer,storage=OverwriteStorage())
    password = models.CharField(max_length=2000, blank=True, null=True)
    barcode = models.CharField(max_length=2000, blank=True, null=True)

    def clean(self):
        if self.ssn=='':
            self.ssn=None

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def program_list(self):
        return ' | '.join([i.name for i in self.program.all()])

    def last_4_ssn(self):
        if self.ssn:
            return u'%s' % self.ssn[-4:]
        return u''

    def image_tag(self,height=42,width=42):
        return mark_safe(u'<img src="%s" height="%s" width="%s"/>' % (self.picture.url,height,width))

    def name(self):
        return '%s %s' % (self.first_name.capitalize(), self.last_name.capitalize())

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    class Meta:
        permissions = (
            ('view_guest', 'Can See Guests'),
            ('manage_guest', 'Can Manage Guests'),
        )


class Permission(models.Model):
    owner = models.ManyToManyField(User,related_name='permission_owner')
    name = models.CharField(max_length=2000, unique=True)
    users = models.ManyToManyField(User, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def user_list(self):
        return ' | '.join([i.__unicode__() for i in self.users.all()])

    class Meta:
        permissions = (
            ('view_permission', 'Can See Permissions'),
            ('manage_permission', 'Can Manage Permissions'),
        )


class Prerequisite(models.Model):
    owner = models.ManyToManyField(User)
    name = models.CharField(max_length=2000, blank=True, null=True)
    prerequisite_form = models.ManyToManyField(Form, blank=True, null=True)
    prerequisite_field = models.ManyToManyField(Field, blank=True, null=True)
    is_complete = models.BooleanField(default=False)
    score_is_greater_than = models.CharField(max_length=2000, blank=True, null=True)
    is_value = models.CharField(max_length=2000, blank=True, null=True)
    contains = models.CharField(max_length=2000, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def form_list(self):
        return ' | '.join([i.name for i in self.prerequisite_form.all()])

    def field_list(self):
        return ' | '.join([i.name for i in self.prerequisite_field.all()])

    class Meta:
        permissions = (
            ('view_prerequisite', 'Can See Prerequisites'),
            ('manage_prerequisite', 'Can Manage Prerequisites'),
        )


class GuestTimeData(models.Model):
    date = models.DateTimeField(null=True, blank=True)
    guest = models.ForeignKey(Guest)
    field = models.ForeignKey(Field)
    value = models.CharField(max_length=20000, blank=True, null=True, default='')


class GuestData(models.Model):
    date = models.DateTimeField(null=True, blank=True)
    guest = models.ForeignKey(Guest)
    field = models.ForeignKey(Field)

report_builder/templates/report_builder/base.html
{% load static from staticfiles %}{% load i18n %}

{% block report_header %}
	{% if user.is_authenticated and user.is_active%}
		<a href="{% url 'index' %}">{% trans 'Home' %}</a> |
		<a href="{% url 'schedule' %}">{% trans 'Schedule' %}</a> | 
	{% else %}
		<a href="/admin/login/?next=/">{% trans 'Login' %}</a>  | 
		<a href="{% url 'schedule' %}">{% trans 'Home' %}</a> |
	{% endif %}
	<a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a> | 
	<a href='/admin/report_builder/'>{% trans 'Reports' %}</a>
<script src="{% static 'report_builder/js/jquery-1.10.2.min.js' %}" type="text/javascript" ></script>
<script src="{% static 'report_builder/js/report_form.js' %}" type="text/javascript" ></script>
<script src="{% static 'report_builder/js/spin.js' %}" type="text/javascript" ></script>
<script src="{% static 'report_builder/js/jquery.spin.js' %}" type="text/javascript" ></script>

<link rel="stylesheet" href="{% static 'jquery-ui-1.9.1/css/smoothness/jquery-ui-1.9.1.custom.min.css' %}" />
<script src="{% static 'jquery-ui-1.9.1/js/jquery-ui-1.9.1.custom.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'report_builder/css/report_form.css' %}" />
{% endblock %}

{% block report_form %}
{% endblock %}

report_builder/templates/report_builder/export_to_report.html
{% extends "report_builder/base.html" %}
{% load url from future %}
{% block content %}
    <script src="{{ STATIC_URL }}report_builder/js/jquery-1.8.2.min.js" type="text/javascript" ></script>
    <script src="{{ STATIC_URL }}report_builder/js/report_form.js" type="text/javascript" ></script>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}report_builder/css/report_form.css" />
    <p>
      Select the report you wish to use. Report filters will be ignored and
      only your checked off items will be reported.
    </p>
    <p>
      Create and manage reports <a href="{% url "admin:report_builder_report_changelist" %}">here</a>.
    </p>
    <p>
      You have selected {{ number_objects}} {{ model }} record{{ number_objects|pluralize }}. Click <a href="{{ admin_url}}">here to go back</a>.
    </p>
    <h2>{{ model|capfirst }} Reports</h2>
    <table class="reports_table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Select and Download</th>
        </tr>
    </thead>
    <tbody>
        {% for report in object_list %}
        <tr>
            <td>
                {{ report.name }}
            </td>
            <td>
                {{ report.description }}
            </td>
            <td>
                {{ report.created }} by {{ report.user_created }}
            </td>
            <td>
                {{ report.modified }} by {{ report.user_modified }}
            </td>
            <td>
                <a href="?ct={{ request.GET.ct }}&ids={{ request.GET.ids }}&download={{ report.id }}">
                  <img style="width: 26px;" src="/static/report_builder/img/download.svg"/>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

report_builder/templates/report_builder/fieldset.html
<li class="draggable" style="list-style: none">
    <span class="button"
        data-name="{% if verbose_name %}{{ verbose_name }}{% else %}{{ field.verbose_name }}{% endif %}"
          data-label="{{ field.name }}"
          data-path="{{ path }}"
          data-path_verbose="{{ path_verbose }}"
          data-choices="{% if field.choices %}true{% endif %}"
          data-root_model="{{ root_model }}"
          data-app_label="{{ app_label }}"
          >
        {% if verbose_name %}{{ verbose_name }}{% else %}{{ field.verbose_name }}{% endif %} [{% if custom %}custom {% endif %}{{ verbose_name_extra }}]
    </span>
</li>

report_builder/templates/report_builder/fieldsets.html
<div class="fieldset">
    <h4>
        {% if 'collapse' in fieldset.1.classes %}
            <a onclick="toggle_collapse(this);" href="javascript:void(0)">{{ fieldset.0 }}</a>
        {% else %}
            {{ fieldset.0 }}
        {% endif %}
    </h4>
    <ul class="{% if 'collapse' in fieldset.1.classes %}collapsed{% endif %}">
        {% for field in fieldset.1.fields %}
            {% if field.1.recursive %}
              {% with template_name="report_builder/fieldsets.html" %}
                  {% include template_name with fieldset=field %}
              {% endwith %}
            {% else %}
              {% include "report_builder/fieldset.html" with verbose_name_extra=field.get_internal_type %}
            {% endif %}
        {% endfor %}
    </ul>
</div>

report_builder/templates/report_builder/html_report.html
{{ message }}
<body>
<table id="html_report_table" class="simple_table">
  <thead>
    <tr>
      {% for header in report.displayfield_set.all %}
        <th style="width: {{ header.width }}px">{{ header.name }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for object in objects_dict %}
      <tr>
        {% for field in object %}
          <td>{{ field }}</td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>
</body>

report_builder/templates/report_builder/report_form.html
{% extends "report_builder/base.html" %}
{% load static from staticfiles %}

{% block report_form %}
<div id="report_container">
  <form action="" method="post">{% csrf_token %}
    <header class="report_top">
      <div id="report_id" data-id="{{ object.id }}">
        <span class="pull_right">
            Last updated: {{ object.modified }}
            Model: {{ object.root_model }}
        </span>
        <span class="pull_left">
            {{ form.name }}   
        </span>
        <span class="fill_area">
            {{ form.description }}
        </span>
      </div>
    </header>
    
    <section class="sidebar">
      <section class="top_half">
        Related Fields:
        <input type="text" class="search_box" onkeyup="filter(this, 'related_fields_ol')" placeholder="Search Fields"/>
        <ol class="tree" id="related_fields_ol" style="padding-left: 0px; margin: 0px;">
          <li class="tree_expanded">
            <span class="button highlight" onclick="show_fields(event, '{{ object.root_model_id }}', '', '');">
              {{ object.root_model }}
            </span>
          </li>
          <li>{% include "report_builder/report_form_related_li.html" %}</li>
        </ol>
      </section>
      <div style="text-align: center;"><img style="width: 2.5em;" src="{% static 'report_builder/img/arrow_down.png' %}"/></div>
      <section class="bottom_half">
        Fields-drag to add
        <input type="text" class="search_box" onkeyup="filter(this, 'field_selection_div')" placeholder="Search Fields"/>
        <div id="field_selection_div">
          {% include "report_builder/report_form_fields_li.html" %}
        </div>
      </section>
 
    </section>
    <section class="main_area">
      <div id="tabs">
        <ul>
          <li><a href="#tabs-1">Report Display Fields</a></li>
          <li><a href="#tabs-2">Report Filters</a></li>
          <li><a href="#tabs-3">Preview Report</a></li>
        </ul>
        <div id="tabs-1">
          <div id="field_list_droppable" class="droppable">
            {{ field_list_formset.management_form }}
            {% for form in field_list_formset %}
              {{ form.errors }}
            {% endfor %}
            <table id="field_list_table" class="simple_table">
              <thead>
                <tr>
                  <th>Order</th>
                  <th>Delete</th>
                  <th>Field</th>
                  <th>Name</th>
                  <th>Sort<span style="padding-left: 1.2em;">Desc?</span></th>
                  <th>Width</th>
                  <th>Aggregate</th>
                  <th>Format</th>
                  <th>Total</th>
                  <th>Group</th>
                </tr>
              </thead>
              <tbody>
                {% for form in field_list_formset %}
                  <tr>
                    <td><span style="cursor: move;" class="ui-icon ui-icon-arrowthick-2-n-s"></span></td>
                    <td>{{ form.DELETE }}<span class="hide_me">{{ form.position }}</span></td>
                    <td>
                      {{ form.id }}
                      {{ form.path_verbose.as_hidden }}
                      {{ form.field }}
                      {{ form.field_verbose.as_hidden }}
                      {{ form.path }}
                      
                      {% if form.path_verbose.value %}
                        ({{ form.path_verbose.value }})
                      {% endif %}
                      {{ form.field_verbose.value }}
                    </td>
                    <td>{{ form.name }}</td>
                    <td>{{ form.sort }}{{ form.sort_reverse }}</td>
                    <td>{{ form.width }}</td>
                    <td onclick="aggregate_tip()">{{ form.aggregate }}</td>
                    <td>{{ form.display_format }}</td>
                    <td>{{ form.total }}</td>
                    <td>{{ form.group }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            Drag fields here
            <div id="tip_area"></div>
          </div>
        </div>
        <div id="tabs-2">
          {{ form.distinct }}{{ form.distinct.label}} (Removes duplicates)
          <div id="field_filter_droppable" class="droppable">
            {{ field_filter_formset.management_form }}
            {% for form in field_filter_formset %}
              {{ form.errors }}
            {% endfor %}
            <table id="field_filter_table" class="simple_table">
              <thead>
                <tr>
                  <th></th>
                  <th>Delete?</th>
                  <th>Field</th>
                  <th>Filter Type</th>
                  <th>Value</th>
                  <th>Exclude?</th>
                </tr>
              </thead>
              <tbody>
                {% for form in field_filter_formset %}
                  <tr>
                    <td><span style="cursor: move;" class="ui-icon ui-icon-arrowthick-2-n-s"></span></td>
                    <td>{{ form.DELETE }}<span class="hide_me">{{ form.position }}</span></td>
                    <td>
                      {{ form.id }}
                      {{ form.path_verbose.as_hidden }}
                      {% if form.path_verbose.value %}
                        ({{ form.path_verbose.value }})
                      {% endif %}
                      {{ form.field }}
                      {{ form.field_verbose.as_hidden }}{{ form.field_verbose.value }}{{ form.path }}
                    </td>
                    <td>{{ form.filter_type }}</td>
                    {% if "DateField" in form.field_verbose.value %}
                        <td class="datepicker">{{ form.filter_value }} {{ form.filter_value2 }}</td>
                        <script>
                            $( ".datepicker input" ).datepicker();
                        </script>
                    {% else %}
                        <td>{{ form.filter_value }} {{ form.filter_value2 }}</td>
                    {% endif %}
                    <td>{{ form.exclude }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            Drag fields here
            <div id="tip_area"></div>
          </div>
        </div>
        <div id="tabs-3">
          {% if async_report %}
            <a href="#" onclick="get_async_report({{ object.id }})">Download full xlsx</a>
          {% else %}
            <a href="{% url "report_download_xlsx" object.id %}">Download full xlsx</a>
          {% endif %}
          <div id="preview_area"></div>
        </div>
      </div>
        <input type="submit" value="Save" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"/>
    </section>
  </form>
</div>
{% endblock %}

report_builder/templates/report_builder/report_form_fields_li.html
{% if fieldsets %}
    {% for fieldset in fieldsets %}
      {% include "report_builder/fieldsets.html" with fieldset=fieldset %}
    {% endfor %}
{% else %}
    <ul>
    {% for field in fields %}
      {% include "report_builder/fieldset.html" with verbose_name_extra=field.get_internal_type %}
    {% endfor %}
    </ul>
{% endif %}

{% if custom_fields %}
    <h4>Custom Fields</h4>
    <ul>
        {% for custom_field in custom_fields %}
            {% include "report_builder/fieldset.html" with field=custom_field verbose_name_extra=custom_field.get_field_type_display verbose_name=custom_field.name custom=True %}
        {% endfor %}
    </ul>
{% endif %}

{% if properties %}
    <h4>Properties</h4>
    <ul>
        {% for property in properties %}
            {% if forloop.first %}
            {% endif %}
            {% include "report_builder/fieldset.html" with field=property verbose_name_extra='property' verbose_name=property.label %}
        {% endfor %}
    </ul>
{% endif %}

report_builder/templates/report_builder/report_form_related_li.html
<ol class="tree" style="padding-left: 0px; margin: 0px;">
    {% for field in related_fields %}
        <li
            class="tree_closed"
            onclick="expand_related(event, '{{ model_ct.id }}', '{{ field.field_name }}', '{{ path }}', '{{ path_verbose }}')">
            <span \
            class="button"
                  onclick="show_fields(event, '{{ model_ct.id }}', '{{ field.field_name }}','{{ path }}', '{{ path_verbose }}');">
                {% if field.verbose_name %}
                    {{ field.verbose_name }}
                    [{{ field.get_internal_type }}]
                {% else %}
                    {{ field.get_accessor_name }}
                {% endif %}
            </span>
        </li>
    {% endfor %}
</ol>